DROP DATABASE IF EXISTS `db_camagru`;

CREATE DATABASE IF NOT EXISTS `db_camagru`;

USE `db_camagru`;

CREATE TABLE IF NOT EXISTS `users` (
	`id`				INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`firstname`			VARCHAR(255) NOT NULL,
	`lastname`			VARCHAR(255) NOT NULL,
	`email`				VARCHAR(255) NOT NULL,
	`username`			VARCHAR(10) NOT NULL,
	`password`			VARCHAR(255) NOT NULL,
	`gender`			VARCHAR(255) NOT NULL,
	`address`			VARCHAR(255) NULL,
	`activationToken`	VARCHAR(255) NULL,
	`recoveryToken`		VARCHAR(255) DEFAULT NULL,
	`notifEmail`		BOOLEAN DEFAULT 1,
	`createdat`			DATETIME DEFAULT CURRENT_TIMESTAMP,
	`modifyat`			DATETIME DEFAULT NULL,
	CONSTRAINT uk_email_username UNIQUE ( email, username )
);

CREATE TABLE IF NOT EXISTS `gallery` (
	`id`				INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`description`		VARCHAR(255) NOT NULL,
	`userid`			INT NOT NULL,
	`src`				VARCHAR(255) NOT NULL,
	`createdat`			DATETIME DEFAULT CURRENT_TIMESTAMP,
	`countlikes`		INT DEFAULT 0,
	`countcomments`		INT DEFAULT 0,
	CONSTRAINT fk_userid_img FOREIGN KEY ( userid ) REFERENCES users( id ) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `likes` (
	`userid`			INT NOT NULL,
	`imgid`				INT NOT NULL,
	`createdat`			DATETIME DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_userid_like FOREIGN KEY ( userid ) REFERENCES users( id ) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_imgid_like FOREIGN KEY ( imgid ) REFERENCES gallery( id ) ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY ( `userid`, `imgid` );
);

CREATE TABLE IF NOT EXISTS `comments` (
	`id`				INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`content`			VARCHAR(255) NOT NULL,
	`userid`			INT NOT NULL,
	`imgid`				INT NOT NULL,
	`createdat`			DATETIME DEFAULT CURRENT_TIMESTAMP,
	`modifyat`			DATETIME DEFAULT NULL,
	CONSTRAINT fk_userid_comment FOREIGN KEY ( userid ) REFERENCES users( id ) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_imgid_comment FOREIGN KEY ( imgid ) REFERENCES gallery( id ) ON DELETE CASCADE ON UPDATE CASCADE
);